# Generated by Django 3.2.9 on 2022-04-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0026_alter_terapeutas_apellidos'),
        ('englishAccess', '0003_auto_20220403_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='therapist',
            field=models.ForeignKey(help_text='Seleccione el terapeuta de este paciente.', on_delete=django.db.models.deletion.CASCADE, to='accesoTerapeutas.terapeutas', verbose_name='Terapeuta'),
        ),
    ]
