# Generated by Django 3.2.9 on 2022-04-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0004_alter_patients_therapist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'ordering': ['-creado'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='lastnames',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='classification5',
            new_name='clasificacion5',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='classification50',
            new_name='clasificacion50',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='classification500',
            new_name='clasificacion500',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='diagnostic',
            new_name='diagnostico',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='therapist',
            new_name='terapeuta',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='username',
            new_name='usuario',
        ),
    ]
