# Generated by Django 3.2.9 on 2022-04-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0006_auto_20220403_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostics',
            old_name='name',
            new_name='nombre',
        ),
    ]
