# Generated by Django 3.2.9 on 2022-04-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0008_auto_20220403_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='clasificacion5',
            new_name='calificacion5',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='clasificacion50',
            new_name='calificacion50',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='clasificacion500',
            new_name='calificacion500',
        ),
    ]
