# Generated by Django 3.2.9 on 2022-04-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0009_auto_20220403_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='birthDate',
            new_name='fechaNacimiento',
        ),
    ]
