# Generated by Django 3.2.9 on 2022-04-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0026_alter_terapeutas_apellidos'),
        ('englishAccess', '0010_rename_birthdate_patients_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='fechaNacimiento',
        ),
        migrations.AddField(
            model_name='patients',
            name='birthDate',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='apellidos',
            field=models.CharField(help_text='Indique los apellidos del paciente.', max_length=60, verbose_name='Lastnames'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='calificacion5',
            field=models.ForeignKey(help_text='Indica la calificacion FMS5 para una distacia de 5 metros', on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_cinco', to='englishAccess.classifications', verbose_name='FMS5 - Classification'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='calificacion50',
            field=models.ForeignKey(help_text='Indica la calificacion FMS50 para una distacia de 50 metros', on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_cincuenta', to='englishAccess.classifications', verbose_name='FMS50 - Classification'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='calificacion500',
            field=models.ForeignKey(help_text='Indica la calificacion FMS500 para una distacia de 500 metros', on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_quinientos', to='englishAccess.classifications', verbose_name='FMS500 - Classification'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='contraseña',
            field=models.CharField(help_text='Indique la contraseña que se usará en las funciones del bot.', max_length=15, verbose_name='Password BOT'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='diagnostico',
            field=models.ForeignKey(help_text='Seleccione el diagnostico de este paciente.', on_delete=django.db.models.deletion.CASCADE, to='englishAccess.diagnostics', verbose_name='Diagnostic'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='nombre',
            field=models.CharField(help_text='Indique el nombre completo del paciente.', max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='telefono',
            field=models.CharField(help_text='Número de teléfono.', max_length=10, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='terapeuta',
            field=models.ForeignKey(help_text='Seleccione el terapeuta de este paciente.', on_delete=django.db.models.deletion.CASCADE, to='accesoTerapeutas.terapeutas', verbose_name='Therapist'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='usuario',
            field=models.CharField(help_text='Indique el usuario que desea asignar al paciente.(Longitud mínima 5 caracteres [a-z, 0-9 y guiones bajos]', max_length=30, verbose_name='User BOT'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='visible',
            field=models.BooleanField(default=True, help_text='Cuando quieras dejar oculto un Paciente, desmarca la casilla', verbose_name='Without hiding'),
        ),
    ]
