# Generated by Django 3.2.9 on 2022-04-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0012_auto_20220405_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ages',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='ages',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='ages',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='extremities',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='extremities',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='extremities',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='laterality',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='laterality',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='laterality',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pcienglish',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='pcienglish',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='pcienglish',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='name',
            new_name='nombre',
        ),
    ]
