# Generated by Django 3.2.9 on 2022-04-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0013_auto_20220405_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapeuticobjective',
            old_name='actupdatedualizado',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='therapeuticobjective',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='therapeuticobjective',
            old_name='name',
            new_name='nombre',
        ),
    ]
