# Generated by Django 3.2.9 on 2022-04-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0014_auto_20220405_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercices',
            name='codigo',
            field=models.CharField(help_text='Indicate the code of the exercise.', max_length=8, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='descripcion',
            field=models.TextField(blank=True, help_text='If you wish, add an explanatory description.', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='diagnostico',
            field=models.ManyToManyField(help_text='Select the diagnoses associated with this exercise.', to='englishAccess.Diagnostics', verbose_name='Diagnostic'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='edad',
            field=models.ManyToManyField(help_text='Select the age ranges for this exercise.', to='englishAccess.Ages', verbose_name='Age ranges'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='extremidades',
            field=models.ManyToManyField(help_text='Select the limbs involved in this exercise.', to='englishAccess.Extremities', verbose_name='Extremities'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='lateralidad',
            field=models.ForeignKey(help_text='Select the laterality of this exercise.', on_delete=django.db.models.deletion.CASCADE, to='englishAccess.laterality', verbose_name='Laterality'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='nombre',
            field=models.CharField(help_text='Give a name for the exercise.', max_length=60, verbose_name='Exercise name'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='objetivoTerapeutico',
            field=models.ManyToManyField(help_text='Select the therapeutic objectives associated with this exercise.', to='englishAccess.TherapeuticObjective', verbose_name='Therapeutic Objectives'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='posicion',
            field=models.ManyToManyField(help_text='Select the position associated with this exercise.', to='englishAccess.Position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='video',
            field=models.FileField(blank=True, help_text='Select the video you want to associate with the exercise. With the following format: code_exercise.mp4', null=True, upload_to='ejercicios', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='visible',
            field=models.BooleanField(default=True, help_text='When you want to hide an exercise, uncheck the box.', verbose_name='Without hiding'),
        ),
    ]
