# Generated by Django 3.2.9 on 2022-04-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0026_alter_terapeutas_apellidos'),
        ('englishAccess', '0015_auto_20220406_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='fechaFinal',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='fechaInicial',
        ),
        migrations.AddField(
            model_name='sessions',
            name='FinalDate',
            field=models.DateField(blank=True, null=True, verbose_name='Final date'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='InitialDate',
            field=models.DateField(blank=True, null=True, verbose_name='Initial date'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='ejercicios',
            field=models.ManyToManyField(help_text='Seleccione los ejercicios para esta sesión.', through='englishAccess.SessionsExercices', to='englishAccess.Exercices', verbose_name='Exercises'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='enviado',
            field=models.BooleanField(default=False, help_text='Si la casilla no se encuentra marcada, las sesion no ha sido programada', verbose_name='Sended'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='paciente',
            field=models.ForeignKey(help_text='Selecciona al paciente asigando para esta sesión.', on_delete=django.db.models.deletion.CASCADE, to='englishAccess.patients', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='periodicidad',
            field=models.IntegerField(default=1, help_text='Indique las veces que puede realizar el paciente esta sesión a lo largo de la semana.', verbose_name='Periodicity'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='terapeuta',
            field=models.ForeignKey(blank=True, help_text='Seleccione el terapeuta de esta sesión.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accesoTerapeutas.terapeutas', verbose_name='Therapist'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='visible',
            field=models.BooleanField(default=True, help_text='Cuando quieras dejar oculto una Sesión, desmarca la casilla', verbose_name='Whithout hiding'),
        ),
    ]
