# Generated by Django 3.2.9 on 2022-04-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0016_auto_20220406_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='FinalDate',
            new_name='finalDate',
        ),
        migrations.RenameField(
            model_name='sessions',
            old_name='InitialDate',
            new_name='initialDate',
        ),
        migrations.AlterField(
            model_name='sessionsexercices',
            name='ejercicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='englishAccess.exercices', verbose_name='Exercises'),
        ),
        migrations.AlterField(
            model_name='sessionsexercices',
            name='repeticiones',
            field=models.SmallIntegerField(default=1, verbose_name='Repetitions'),
        ),
        migrations.AlterField(
            model_name='sessionsexercices',
            name='sesiones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='englishAccess.sessions', verbose_name='Sessions'),
        ),
    ]
