# Generated by Django 3.2.9 on 2022-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0017_auto_20220406_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentpatiens',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='assessmentpatiens',
            old_name='session',
            new_name='sesion',
        ),
        migrations.RenameField(
            model_name='assessmentpatiens',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='assessmentpatiens',
            old_name='val1',
            new_name='valoracion1',
        ),
        migrations.RenameField(
            model_name='assessmentpatiens',
            old_name='val2',
            new_name='valoracion2',
        ),
        migrations.RenameField(
            model_name='assessmentpatiens',
            old_name='val3',
            new_name='valoracion3',
        ),
        migrations.RenameField(
            model_name='assessmentpatiens',
            old_name='val4',
            new_name='valoracion4',
        ),
        migrations.RenameField(
            model_name='assessmentpatiens',
            old_name='val5',
            new_name='valoracion5',
        ),
        migrations.RemoveField(
            model_name='assessmentpatiens',
            name='exercise',
        ),
        migrations.AddField(
            model_name='assessmentpatiens',
            name='ejercicio',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ejercicio'),
        ),
    ]
