# Generated by Django 3.2.9 on 2022-06-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0020_rename_birthdate_patients_birth_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TherapeuticObjective',
            new_name='Therapeutic_Objective',
        ),
        migrations.RemoveField(
            model_name='exercices',
            name='objetivoTerapeutico',
        ),
        migrations.AddField(
            model_name='exercices',
            name='objetivo_Terapeutico',
            field=models.ManyToManyField(help_text='Select the therapeutic objectives associated with this exercise.', to='englishAccess.Therapeutic_Objective', verbose_name='Therapeutic Objectives'),
        ),
    ]
