# Generated by Django 3.2.9 on 2022-06-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('englishAccess', '0021_auto_20220617_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Add a new monitoring part.', max_length=40)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sensor Monitoring',
                'verbose_name_plural': 'Sensor Monitoring',
            },
        ),
        migrations.AddField(
            model_name='exercices',
            name='monitoreo_Sensores',
            field=models.ForeignKey(blank=True, help_text='Select the part to monitor.', null=True, on_delete=django.db.models.deletion.CASCADE, to='englishAccess.sensor_monitoring', verbose_name='Sensor Monitoring'),
        ),
    ]
