# Generated by Django 3.2.9 on 2021-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0002_auto_20211128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='apellidos',
            field=models.CharField(help_text='Indique los apellidos del paciente.', max_length=60, verbose_name='Apellidos'),
        ),
    ]
