# Generated by Django 3.2.9 on 2021-12-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0003_alter_pacientes_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='email',
            field=models.EmailField(help_text='Correo electróncio.', max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='telefono',
            field=models.CharField(help_text='Número de teléfono.', max_length=10, verbose_name='Telefono'),
        ),
    ]
