# Generated by Django 3.2.9 on 2021-12-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0004_auto_20211211_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
