# Generated by Django 3.2.9 on 2021-12-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0005_alter_pacientes_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariopacientes',
            name='paciente',
            field=models.ManyToManyField(help_text='Seleccione el paciente', to='accesoTerapeutas.Pacientes', verbose_name='Paciente'),
        ),
    ]
