# Generated by Django 3.2.9 on 2021-12-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0006_formulariopacientes_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariopacientes',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='formulariopacientes',
            name='usuario',
        ),
    ]
