# Generated by Django 3.2.9 on 2021-12-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0007_auto_20211217_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariopacientes',
            name='paciente',
        ),
        migrations.AddField(
            model_name='formulariopacientes',
            name='paciente',
            field=models.ForeignKey(blank=True, help_text='Selecciona al paciente asigando para esta sesión.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accesoTerapeutas.pacientes', verbose_name='Paciente'),
        ),
    ]
