# Generated by Django 3.2.9 on 2021-12-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0009_alter_formulariopacientes_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiones',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Final'),
        ),
        migrations.AlterField(
            model_name='sesiones',
            name='fechaInicial',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
