# Generated by Django 3.2.9 on 2021-12-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0010_auto_20211224_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiones',
            name='fechaFinal',
            field=models.DateField(verbose_name='Fecha de Final'),
        ),
        migrations.AlterField(
            model_name='sesiones',
            name='fechaInicial',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
    ]
