# Generated by Django 3.2.9 on 2022-02-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0011_auto_20211224_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicios',
            name='video',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='ejercicios')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesoTerapeutas.ejercicios')),
            ],
        ),
    ]
