# Generated by Django 3.2.9 on 2022-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0013_auto_20220217_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticos',
            name='english_name',
            field=models.CharField(blank=True, help_text='Add a new diagnostic.', max_length=40, null=True),
        ),
    ]
