# Generated by Django 3.2.9 on 2022-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0015_auto_20220322_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='edad',
            name='english_name',
            field=models.CharField(blank=True, help_text='Añada un nuevo rango de edad', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='extremidades',
            name='english_name',
            field=models.CharField(blank=True, help_text='Add a new name for a new extremity', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='lateralidad',
            name='english_name',
            field=models.CharField(blank=True, help_text='Add a new name for a new laterality', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='objetivoterapeutico',
            name='english_name',
            field=models.CharField(blank=True, help_text='Add a new therapeutic objective', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='gmfcs',
            name='nombre',
            field=models.CharField(help_text='Añada un nuevo nivel de función motora gruesa', max_length=40),
        ),
        migrations.AlterField(
            model_name='lateralidad',
            name='nombre',
            field=models.CharField(help_text='Añada un nuevo nombre de lateralidad', max_length=40),
        ),
        migrations.AlterField(
            model_name='macs',
            name='nombre',
            field=models.CharField(help_text='Añada un nuevo nivel de habilidad manual', max_length=40),
        ),
        migrations.AlterField(
            model_name='objetivoterapeutico',
            name='nombre',
            field=models.CharField(help_text='Añada un nuevo objetivo terapéutivo', max_length=40),
        ),
        migrations.AlterField(
            model_name='pci',
            name='nombre',
            field=models.CharField(help_text='Añada una nuevo PCI', max_length=40),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(blank=True, help_text='Add a new posittion', max_length=40, null=True),
        ),
    ]
