# Generated by Django 3.2.9 on 2022-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0016_auto_20220322_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='english_name',
            field=models.CharField(blank=True, help_text='Add a new posittion', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(blank=True, help_text='Añada una nueva posición', max_length=40, null=True),
        ),
    ]
