# Generated by Django 3.2.9 on 2022-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0017_auto_20220322_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='pci',
            name='english_name',
            field=models.CharField(blank=True, help_text='Añada una nuevo PCI', max_length=40, null=True),
        ),
    ]
