# Generated by Django 3.2.9 on 2022-04-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0019_auto_20220402_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idiomas',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AddField(
            model_name='idiomas',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
