# Generated by Django 3.2.9 on 2022-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0023_remove_terapeutas_nombreusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeutas',
            name='nombreUsuario',
            field=models.CharField(blank=True, help_text='Indique el nombre de usuario del terapeuta.', max_length=30, null=True, verbose_name='Usuario'),
        ),
    ]
