# Generated by Django 3.2.9 on 2022-04-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0024_terapeutas_nombreusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapeutas',
            name='nombreUsuario',
        ),
    ]
