# Generated by Django 3.2.9 on 2022-04-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0026_alter_terapeutas_apellidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticos',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='edad',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='ejercicios',
            name='english_description',
        ),
        migrations.RemoveField(
            model_name='ejercicios',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='extremidades',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='lateralidad',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='objetivoterapeutico',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='pci',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='english_name',
        ),
    ]
