# Generated by Django 3.2.9 on 2022-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0027_auto_20220406_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionpacientes',
            name='ejercicio',
            field=models.CharField(max_length=30, verbose_name='Ejercicio'),
        ),
    ]
