# Generated by Django 3.2.9 on 2022-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0028_alter_valoracionpacientes_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiones',
            name='informe',
            field=models.BooleanField(blank=True, null=True, verbose_name='Informe'),
        ),
    ]
