# Generated by Django 3.2.9 on 2022-04-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0029_sesiones_informe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesiones',
            name='informe',
        ),
    ]
