# Generated by Django 3.2.9 on 2022-06-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0030_remove_sesiones_informe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='terapeuta',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='terapeuta',
            field=models.ManyToManyField(help_text='Seleccione el terapeuta de este paciente.', to='accesoTerapeutas.Terapeutas', verbose_name='Terapeuta'),
        ),
    ]
