# Generated by Django 3.2.9 on 2022-06-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0031_auto_20220608_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesiones',
            old_name='fechaFinal',
            new_name='fecha_Final',
        ),
        migrations.RenameField(
            model_name='sesiones',
            old_name='fechaInicial',
            new_name='fecha_Inicial',
        ),
    ]
