# Generated by Django 3.2.9 on 2022-06-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0032_auto_20220613_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='fechaNacimiento',
            new_name='fecha_Nacimiento',
        ),
    ]
