# Generated by Django 3.2.9 on 2022-06-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesoTerapeutas', '0034_auto_20220617_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo_Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Añada una nueva parte para monitorear', max_length=40)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monitoreo de Sensores',
                'verbose_name_plural': 'Monitoreo de Sensores',
            },
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='monitoreo_Sensores',
            field=models.ForeignKey(blank=True, help_text='Seleccione la parte a monitorear.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accesoTerapeutas.monitoreo_sensores', verbose_name='Monitoreo de Sensores'),
        ),
    ]
